version: 0.2
phases:
  install:
    commands:
      - echo "Running pre-build installs"
      - apt-get update
      - apt-get install zip
      - apt-get install python
      - apt-get -y install python-pip
      - apt-get -y install wget
      - wget https://releases.hashicorp.com/terraform/0.8.5/terraform_0.8.5_linux_386.zip
      - unzip terraform_0.8.5_linux_386.zip
      - mv terraform /usr/local/bin/
      - export PATH=$PATH:/terraform-path/
  pre_build:
    commands:
      - echo "Started building the package"
  build:
    commands:
      - echo "terraform package"
      - terraform plan
  post_build:
    commands:
      - echo "Finished building the package"

